name: CI
on:
  push:
    branches: [master]

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 레파지토리 check out
      - name: Checkout source code.
        uses: actions/checkout@v2

      # node.js 버전 12
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      # Set Dependencies
      - name: Install Dependencies
        run: npm install

      # Author identity
      - name: Github auth and commit
        env:
          MY_EMAIL: kkum9408@gmail.com
          MY_NAME: dongwon
        run: |
          git config --global user.email $MY_EMAIL
          git config --global user.name $MY_NAME

      # Build
      - name: Build
        run: yarn preorder

      # Deploy
      - name: Deploy
        run: yarn deploy
